Repository Shopify/dawn, pull requests merged in 2021-11, with the labels that each got.

#807 Fix variant spacing on product page
  assets/section-main-product.css
  sections/main-product.liquid
Labels: bug

#811 Add unit price to cart
  assets/component-cart-items.css
  sections/main-cart-items.liquid
Labels: 🎨 Design

#918 Image with text section - Apply global textbox and media settings
  assets/component-image-with-text.css
  sections/image-with-text.liquid
Labels: cla-needed, global settings

#917 Split popup and drawer settings
  assets/base.css
  assets/component-cart-notification.css
  assets/component-facets.css
  assets/component-menu-drawer.css
  assets/component-pickup-availability.css
  assets/component-predictive-search.css
  assets/disclosure.css
  assets/section-main-product.css
  config/settings_schema.json
  layout/theme.liquid
  locales/en.default.schema.json
Labels: global settings
