Repository Shopify/dawn, pull requests merged in 2021-12, with the labels that each got.

#900 Add image banner settings
  assets/component-newsletter.css
  assets/section-email-signup-banner.css
  assets/section-image-banner.css
  assets/section-password.css
  locales/cs.schema.json
  locales/da.schema.json
  locales/de.schema.json
  locales/en.default.schema.json
  locales/es.schema.json
  locales/fi.schema.json
  locales/fr.schema.json
  locales/it.schema.json
  locales/ja.schema.json
  locales/ko.schema.json
  locales/nb.schema.json
  locales/nl.schema.json
  locales/pl.schema.json
  locales/pt-BR.schema.json
  locales/pt-PT.schema.json
  locales/sv.schema.json
  locales/th.schema.json
  locales/tr.schema.json
  locales/vi.schema.json
  locales/zh-CN.schema.json
  locales/zh-TW.schema.json
  sections/email-signup-banner.liquid
  sections/image-banner.liquid
  templates/index.json
Labels: enhancement

#1014 Fix collage section product and collection card image size
  assets/collage.css
  assets/component-card.css
  assets/component-modal-video.css
  assets/section-main-product.css
  sections/collage.liquid
  snippets/card-collection.liquid
  snippets/card-product.liquid
Labels: global settings

#1024 add border radius to dynamic checkout buttons
  assets/base.css
  assets/component-cart.css
  assets/component-image-with-text.css
  assets/section-main-product.css
Labels: global settings

#1042 Update global settings range values
  config/settings_schema.json
Labels: Severity: 1

#1052 Pill shadow updates
  assets/section-main-product.css
Labels: Severity: 1

#1044 Settings content naming update
  config/settings_schema.json
  locales/en.default.schema.json
Labels: Severity: 1

#1050 Add content container to sections and update styling
  assets/base.css
  assets/component-image-with-text.css
  assets/component-slideshow.css
  assets/section-email-signup-banner.css
  assets/section-image-banner.css
  assets/section-multicolumn.css
  sections/email-signup-banner.liquid
  sections/image-banner.liquid
  sections/image-with-text.liquid
  sections/multicolumn.liquid
  sections/newsletter.liquid
  sections/rich-text.liquid
  sections/slideshow.liquid
Labels: Severity: 1

#1069 Revise range values
  config/settings_schema.json
Labels: Severity: 1, global settings

#1064 Refactor button styles
  assets/base.css
  assets/component-cart-items.css
  assets/component-cart.css
  assets/component-facets.css
  assets/component-image-with-text.css
  assets/customer.css
  assets/section-featured-product.css
  assets/section-image-banner.css
  assets/section-main-product.css
  assets/section-rich-text.css
  layout/theme.liquid
Labels: Severity: 1, global settings
