Repository Shopify/dawn, pull requests merged in 2021-09, with the labels that each got.

#576 Misc design refinements
  assets/base.css
  assets/collage.css
  assets/component-article-card.css
  assets/component-collection-hero.css
  assets/component-image-with-text.css
  assets/component-list-social.css
  assets/component-loading-overlay.css
  assets/component-menu-drawer.css
  assets/component-pagination.css
  assets/component-product-grid.css
  assets/newsletter-section.css
  assets/product-form.js
  assets/section-blog-post.css
  assets/section-collection-list.css
  assets/section-featured-blog.css
  assets/section-multicolumn.css
  assets/section-rich-text.css
  assets/template-collection.css
  assets/video-section.css
  layout/password.liquid
  layout/theme.liquid
  sections/collage.liquid
  sections/featured-product.liquid
  sections/footer.liquid
  sections/header.liquid
  sections/main-password-footer.liquid
  sections/main-product.liquid
Labels: Severity: 1, enhancement, 🎨 Design

#631 Fix long menu overlap
  assets/base.css
Labels: bug

#629 Add missing tax/vat below price
  assets/section-main-product.css
  locales/bg-BG.json
  locales/cs.json
  locales/da.json
  locales/de.json
  locales/el.json
  locales/en.default.json
  locales/es.json
  locales/fi.json
  locales/fr.json
  locales/hr-HR.json
  locales/hu.json
  locales/id.json
  locales/it.json
  locales/ja.json
  locales/ko.json
  locales/lt-LT.json
  locales/nb.json
  locales/nl.json
  locales/pl.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro-RO.json
  locales/ru.json
  locales/sk-SK.json
  locales/sl-SI.json
  locales/sv.json
  locales/th.json
  locales/tr.json
  locales/vi.json
  locales/zh-CN.json
  locales/zh-TW.json
  sections/featured-product.liquid
  sections/main-product.liquid
Labels: bug

#655 Remove white space mobile view for product page
  assets/component-product-model.css
  assets/product-model.js
Labels: bug

#663 Update banner width
  assets/section-image-banner.css
Labels: 🎨 Design

#679 Fix rich media issues (multiple 3D models, video looping and media pausing)
  assets/global.js
  sections/featured-product.liquid
  sections/main-product.liquid
  snippets/product-media.liquid
Labels: bug
