Repository Shopify/dawn, pull requests merged in 2022-01, with the labels that each got.

#1140 Fix border card hover safari
  assets/component-card.css
Labels: cla-needed

#1034 Adding colour scheme settings to various sections
  assets/base.css
  assets/collage.css
  assets/component-cart-items.css
  assets/component-collection-hero.css
  assets/component-facets.css
  assets/global.js
  assets/section-collection-list.css
  assets/section-featured-blog.css
  assets/section-featured-product.css
  assets/section-multicolumn.css
  assets/section-product-recommendations.css
  assets/template-collection.css
  locales/cs.schema.json
  locales/da.schema.json
  locales/de.schema.json
  locales/en.default.schema.json
  locales/es.schema.json
  locales/fi.schema.json
  locales/fr.schema.json
  locales/it.schema.json
  locales/ja.schema.json
  locales/ko.schema.json
  locales/nb.schema.json
  locales/nl.schema.json
  locales/pl.schema.json
  locales/pt-BR.schema.json
  locales/pt-PT.schema.json
  locales/sv.schema.json
  locales/th.schema.json
  locales/tr.schema.json
  locales/vi.schema.json
  locales/zh-CN.schema.json
  locales/zh-TW.schema.json
  sections/collage.liquid
  sections/collapsible-content.liquid
  sections/collection-list.liquid
  sections/contact-form.liquid
  sections/custom-liquid.liquid
  sections/featured-blog.liquid
  sections/featured-collection.liquid
  sections/featured-product.liquid
  sections/main-cart-footer.liquid
  sections/main-collection-banner.liquid
  sections/main-collection-product-grid.liquid
  sections/multicolumn.liquid
  sections/page.liquid
  sections/product-recommendations.liquid
  sections/video.liquid
Labels: Severity: 1

#1097 Global styling: Inputs styling not applied consistently
  assets/base.css
  assets/component-cart-items.css
  assets/component-cart.css
  assets/component-facets.css
  assets/component-newsletter.css
  assets/component-search.css
  assets/customer.css
  assets/section-footer.css
  assets/section-main-product.css
  layout/theme.liquid
  sections/featured-product.liquid
  sections/header.liquid
  sections/main-cart-footer.liquid
  sections/main-product.liquid
Labels: cla-needed

#1221 Fix product thumbnail active state
  assets/section-main-product.css
Labels: Severity: 1, bug

#1201 Update padding input
  assets/base.css
  assets/component-cart.css
  assets/section-footer.css
Labels: cla-needed

#1235 Update footer text block default copy
  sections/footer.liquid
Labels: Severity: 1

#1228 Added a padding setting to page and fixed article bottom margin
  assets/section-blog-post.css
  sections/main-article.liquid
  sections/main-page.liquid
Labels: Severity: 1, bug

#1257 Fix image width with higher specificity selector
  assets/section-multicolumn.css
  sections/multicolumn.liquid
Labels: bug

#1242 Fix menu drawer - enable body click to close menu
  assets/global.js
Labels: Severity: 2
